- name: sol validator setup
  become: true
  become_user: solana
  copy:
    src: validator.sh
    dest: /home/solana/validator.sh
    owner: solana
    group: solana
    mode: "0755"

- name: setup sol.service
  become: true
  become_user: root
  copy:
    src: sol.service
    dest: /etc/systemd/system/sol.service
    owner: root
    group: root
    mode: "0755"

- name: copy start.sh
  become: true
  become_user: solana
  copy:
    src: start.sh
    dest: /home/solana/start.sh
    owner: solana
    group: solana
    mode: "0755"